/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.travel.govibe;

/**
 *
 * @author Dilshith
 */
public class c_login extends javax.swing.JFrame {

    /**
     * Creates new form c_login
     */
    public c_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c_usernamefield = new javax.swing.JTextField();
        c_passfield = new javax.swing.JPasswordField();
        c_loginbutton = new javax.swing.JButton();
        c_passreset = new javax.swing.JLabel();
        c_signup = new javax.swing.JLabel();
        ui_customerborder = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Your username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));
        jPanel1.add(c_usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 270, 30));

        c_passfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_passfieldActionPerformed(evt);
            }
        });
        jPanel1.add(c_passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 270, 30));

        c_loginbutton.setBackground(new java.awt.Color(26, 234, 182));
        c_loginbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        c_loginbutton.setForeground(new java.awt.Color(51, 51, 51));
        c_loginbutton.setText("Log in");
        c_loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_loginbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(c_loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 270, 30));

        c_passreset.setForeground(new java.awt.Color(51, 51, 51));
        c_passreset.setText("Reset password?");
        c_passreset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_passresetMouseClicked(evt);
            }
        });
        jPanel1.add(c_passreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        c_signup.setForeground(new java.awt.Color(51, 51, 51));
        c_signup.setText("No account? Create One");
        c_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_signupMouseClicked(evt);
            }
        });
        jPanel1.add(c_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        ui_customerborder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ui_customerborder.setForeground(new java.awt.Color(0, 1, 0));
        ui_customerborder.setText("                                        CUSTOMER LOGIN");
        ui_customerborder.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ui_customerborder.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(ui_customerborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 360, 20));

        jPanel2.setBackground(new java.awt.Color(26, 234, 182));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("WELCOME");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 203, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BACK!");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void c_loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_loginbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_loginbuttonActionPerformed

    private void c_passfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_passfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_passfieldActionPerformed

    private void c_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_signupMouseClicked
        // TODO add your handling code here:
        c_signup cs=new c_signup();
        cs.show();
        dispose();
    }//GEN-LAST:event_c_signupMouseClicked

    private void c_passresetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_passresetMouseClicked
        // TODO add your handling code here:
        c_resetpass rp=new c_resetpass();
        rp.show();
        dispose();
    }//GEN-LAST:event_c_passresetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(c_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(c_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(c_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(c_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new c_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c_loginbutton;
    private javax.swing.JPasswordField c_passfield;
    private javax.swing.JLabel c_passreset;
    private javax.swing.JLabel c_signup;
    private javax.swing.JTextField c_usernamefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel ui_customerborder;
    // End of variables declaration//GEN-END:variables
}
